### ISSUE TITLE
Links to USGS metadata for KH-4B are broken

### ISSUE THREAD

**Issue by dshean** [engelsjk/keyhole#1]
Thanks for this amazing tool (and quick/easy viz of scanned images)!  

Links to USGS metadata from a few spot checks for samples for records over High-Mountain Asia worked fine for KH-9, but not earlier KH-4B:

Example: DS1101-1039DF073
https://earthexplorer.usgs.gov/scene/metadata/full/5e7c41f3ffaaf662/DS1101-1039DF073/

> An error occurred
> An error occurred during execution; please try again later.

Could also be on EarthExplorer API end.

**Comment by engelsjk** [comment]
Thanks for spotting that. Looks like it was a bug in the data processing stage that I had recently updated. 

3d3be4fdd29d1cb0bec684e56c71b6f91caee9f7 I've pushed a fix to the web app so those metadata links should be working again now.
